### ISSUE TITLE
Add browser Discord support?

### ISSUE THREAD

**Issue by ttang4299** [andrewburgess/steamdeck-discord-status#1]
Hi, I'm currently using browser Discord to be able to use screenshare with audio (the official Discord app doesn't support screenshare with audio on Linux). I would love to be able to only depend on browser Discord instead of two instances of Discord, and I'm willing to install a browser extension if needed (I am using Chrome by the way). Please consider it!

**Comment by lividhen** [comment]
Also using webcord as I have frequent freezing issues with the official client.

**Comment by andrewburgess** [comment]
I don't think this would be possible (at least, within the scope of how this plugin works). The browser version of Discord doesn't expose a communication channel for the plugin like the native app does, so I'm not aware of a way to set this up
