### ISSUE TITLE
Discord Status does not (always) show up for others but only myself

### ISSUE THREAD

**Issue by VortexAcherontic** [andrewburgess/steamdeck-discord-status#10]
The Discord Status does not work reliable.
It shows always for the user itself, however it does not on Servers not created by the user.

Here are some examples, the one who is me should be obvious.

Sever created by me:
![server_by_vortex](https://github.com/andrewburgess/steamdeck-discord-status/assets/11244092/dedb43f4-7ce5-47d7-8707-e2996fcce614)

Server not created by me:
![server_not_by_vortex](https://github.com/andrewburgess/steamdeck-discord-status/assets/11244092/ec8a5aed-8d9d-4124-9ac1-b48befe4acaa)

Also it makes a difference if you previously clicked on the Discord Status of the user on a server created by them and then doing the same on a different server.

Steps to reproduce:

main user := is the user running on Steam Deck with Discord Status Plug-in

Variant 1:
1) Create new discord account
2) Join server **not** created by main user
3) No Status

Variant 2:
1) Create new user
2) Join server created by main user
3) click on main user -> See Status

Variant 3:
1) Create new user
2) Join server created by main user
3) Click on main user -> See status
4) Join a different server **not** created by the main user
5) Click on main user -> See status
6) Leave server created by main user previously joined
7) Click on main user on server **not** created by them -> Status missing again

**Comment by andrewburgess** [comment]
Don't think this is plugin related
