### ISSUE TITLE
Steam OS 3.5.19 Killed the plugin.

### ISSUE THREAD

**Issue by jammermt99** [andrewburgess/steamdeck-discord-status#11]
Just the title it stopped working.

**Comment by irondead5** [comment]
It is not working for me, something about the type error undefined. Probably now something is coming up at the beginning of the code undefined, perhaps it could be fixed with just adding a '?' in the variable that is getting evaluated

**Comment by Shrey1517** [comment]
yeah it doesnt work with the version of steam os that came out a couple months ago and still seems to not be updated to work on it

**Comment by Gildedter** [comment]
mine displays the status in game mode, but borked on the menu with an error

**Comment by andrewburgess** [comment]
Should be fixed when https://github.com/SteamDeckHomebrew/decky-plugin-database/pull/627 is deployed (waiting on review from them)
