### ISSUE TITLE
Uploading the newest version to the decky store

### ISSUE THREAD

**Issue by PartyWumpus** [andrewburgess/steamdeck-discord-status#12]
Hey, I noticed that you made a 1.3.0 tag a while ago, but you never PRed it to the store. I'm happy to open the PR for you if you'd like, but it seems a shame to have the version in the store out of date for no reason.

Not sure what the best way to communicate with you is, so I thought I'd just open an issue here.

**Comment by andrewburgess** [comment]
Yeah, I was going to rework a few things for the plugin, but then had other stuff come up. I'm not sure if it's in a fully working state at the moment after the recent OS updates either.

I might be able to devote some time to working on it in the next few days and will see if I can get a version together for publishing

**Comment by PartyWumpus** [comment]
> Yeah, I was going to rework a few things for the plugin, but then had other stuff come up. I'm not sure if it's in a fully working state at the moment after the recent OS updates either.
> 
> I might be able to devote some time to working on it in the next few days and will see if I can get a version together for publishing

Nice. I'd imagine it is working, as you've moved over to global dfl, but obviously worth checking.

**Comment by PartyWumpus** [comment]
[pr has been opened](https://github.com/SteamDeckHomebrew/decky-plugin-database/pull/627)
