### ISSUE TITLE
Open a support thread in the Steam Deck Homebrew server?

### ISSUE THREAD

**Issue by ttang4299** [andrewburgess/steamdeck-discord-status#14]
Might be useful for those in that server who are less literate in how to use GitHub to directly communicate with the developer.

**Comment by andrewburgess** [comment]
No thanks. This project is a hacky toy project to get rich presence in Discord, and I'm not particularly interested in going much beyond what I've already done (to be frank, I hardly use my own plugin anymore 🤷)
