### ISSUE TITLE
Implementation of arrpc rpc server?

### ISSUE THREAD

**Issue by cyclone018** [andrewburgess/steamdeck-discord-status#16]
Hello, 
This is a very neat plugin. Thanks for your hard work! I do have a suggestion, have you thought about using arrpc in your plugin?

Im pretty sure that this opens a rpc server on the deck and interfaces with the web version of discord and allows the change of status. (Like Deckcord)

Or maybe a tiny client that sends info to an IP (that being your pc with discord running) and updates that.

What im trying to get at is removing the requirement to have discord installed locally and having that running in the background . (highly annoying when it spams keyboard when playing a game)

**Comment by andrewburgess** [comment]
Thanks for the suggestion, glad it's working for you.

I don't think I'm going to go down that path though. It would add a lot of extra complication and seems better suited as a separate project (solving a similar issue but in a pretty different way).

I haven't run into the issue of spamming keyboard while another game has focus. I have my controller layout for Discord set to the "Web Browser" one which might help (I don't think it maps any key presses that would cause issues)
