### ISSUE TITLE
Now working in decky 3.0 but need something changed back

### ISSUE THREAD

**Issue by Shrey1517** [andrewburgess/steamdeck-discord-status#17]
The plugin used to say that you’re playing thr name of the game but now it says playing steam deck and you have to click on the profile to see what game. can you change it so the activity shows up as playing the name of the game instead?

**Comment by andrewburgess** [comment]
That's how the previous iteration would have worked as well (used a custom Discord application as the one to report).

I'm working on fixing that though in [this branch](https://github.com/andrewburgess/steamdeck-discord-status/tree/feature/dynamic-client-id). Still testing things but might be able to deploy a new version soon that will use the game's client ID for reporting if it can be detected

**Comment by Shrey1517** [comment]
> That's how the previous iteration would have worked as well (used a custom Discord application as the one to report).
> 
> I'm working on fixing that though in [this branch](https://github.com/andrewburgess/steamdeck-discord-status/tree/feature/dynamic-client-id). Still testing things but might be able to deploy a new version soon that will use the game's client ID for reporting if it can be detected

I see thanks, any eta for it’s release?

**Comment by andrewburgess** [comment]
No specific ETA. Might be able to work on it a bit more this weekend and can maybe put something together

**Comment by Shrey1517** [comment]
ok thanks

**Comment by andrewburgess** [comment]
When https://github.com/SteamDeckHomebrew/decky-plugin-database/pull/697 is merged and the store updated, then this should be in place.

**Comment by solaflareayz** [comment]
wow that was fast, thanks. i’ll check every couple hours to see when it’s updated

**Comment by andrewburgess** [comment]
It'll take a bit to make it to the decky store. They usually do a few rounds of review and testing. You can subscribe to updates on the PR I linked to track progress

**Comment by solaflareayz** [comment]
It still seems not to be implemented, does it usually take this long?

**Comment by andrewburgess** [comment]
Yeah, it can take that long. I don't really have any control over plugin releases, so it's mainly down to whenever someone else on the decky plugin side can review things and kick off a plugin deployment
