### ISSUE TITLE
Playing Status

### ISSUE THREAD

**Issue by LeJonathan** [andrewburgess/steamdeck-discord-status#2]
Hi, would it be possible to include an option for what's displayed in the playing status?

For example instead of "Playing Steam Deck" we could change it to directly say what game's being played.

**Comment by andrewburgess** [comment]
I've looked into this a bit, and I'm not sure it would be possible unfortunately.

The only way that I could figure out how to make it work was to register a Discord app called "Steam Deck", and then have the plugin tell Discord that that app is currently active, and update the rich presence details with the current game that's being played.

**Comment by LeJonathan** [comment]
Ah unfortunate. Thanks anyways!
Love the plugin.

**Comment by andrewburgess** [comment]
I'm glad it's working for you!

**Comment by justin-tasi** [comment]
Deckcord does what you are asking for but it's very buggy: https://github.com/marios8543/Deckcord
