### ISSUE TITLE
Possible bug???

### ISSUE THREAD

**Issue by Shadow322** [andrewburgess/steamdeck-discord-status#3]
Like say im playing GameCube using emudeck when i try to exit game it crash's and game still running and now to exit i have to reboot the deck

**Comment by andrewburgess** [comment]
I don't think this is related to the plugin. There was a [known issue](https://github.com/ValveSoftware/steam-for-linux/issues/8474) with running two or more non-Steam apps and having issues with closing them. Valve seems to have fixed it in a beta build on Jan 5 (https://steamcommunity.com/app/1675200/eventcomments/37611016931512156910) but I'm not sure if that fix has made it to stable yet.

**Comment by Shadow322** [comment]
It is related to the plug-in because once I disabled/Uninstaller this plug-in the problem no longer exists then I reinstall it comes right back
