### ISSUE TITLE
Decky Store?

### ISSUE THREAD

**Issue by Shadow322** [andrewburgess/steamdeck-discord-status#4]
How do we get v1.1.0 of this plugin onto the Decky Store?

**Comment by andrewburgess** [comment]
It will be deployed when https://github.com/SteamDeckHomebrew/decky-plugin-database/pull/213 is reviewed and merged.

Note that v1.1.0 doesn't address https://github.com/andrewburgess/steamdeck-discord-status/issues/3
If you are having issues with closing non Steam apps, try switch Steam to the beta branch, where Valve has addressed the issue.
