### ISSUE TITLE
Not connecting to Discord

### ISSUE THREAD

**Issue by mm12** [andrewburgess/steamdeck-discord-status#5]
I have uninstalled and reinstalled both the plugin and discord, and it is still failing to connect. Is this a bug?

**Comment by Chirishman** [comment]
I’m having the same problem. @andrewburgess can you please add some kind of instructions on using this properly to the readme?

**Comment by andrewburgess** [comment]
Hopefully working in new update, make sure to get latest version of DeckyLoader as well
