### ISSUE TITLE
Add toggle to enable rich presence

### ISSUE THREAD

**Issue by rsubtil** [andrewburgess/steamdeck-discord-status#7]
Would be cool to offer a toggle/switch to quickly enable this plugin or not. Sometimes I want to disable this plugin but the only option is to either close Discord, or uninstall the plugin.

**Comment by andrewburgess** [comment]
This will be supported when https://github.com/andrewburgess/steamdeck-discord-status/releases/tag/v1.3.1 is released

Currently waiting for verification from https://github.com/SteamDeckHomebrew/decky-plugin-database/pull/627
